// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	IsDeleted pgtype.Bool
}
